# Generated by Django 5.1.4 on 2024-12-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_email_app', '0002_rename_desgination_employee_f_desgination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='f_Desgination',
            new_name='f_Designation',
        ),
    ]
